import * as XLSX from 'xlsx';

export const FINANCIERA_HEADERS = [
  'nombre_financiera',
  'tipo_producto',
  'perfil_cliente',
  'monto_minimo',
  'monto_maximo',
  'plazo_meses',
  'tasa_interes',
  'comision_apertura',
  'destinos_credito',
  'edad_minima',
  'edad_maxima',
  'antiguedad_meses_min',
  'ingreso_mensual_min',
  'ingreso_anual_min',
  'ventas_terminal_min',
  'buro_accionista_min',
  'buro_empresa_min',
  'buro_persona_fisica_min',
  'permite_atrasos_buro',
  'tolerancia_atrasos_max',
  'tipo_garantia',
  'requiere_aval',
  'requiere_sat_ciec',
  'requiere_estados_financieros',
  'opinion_cumplimiento',
  'participacion_ventas_gob_max',
  'requiere_creditos_vigentes',
  'giros_prohibidos',
  'presencia',
  'tiempo_respuesta',
  'comision_apertura_superadmin',
  'comision_sobretasa_superadmin',
  'comision_renovacion_superadmin',
  'comision_apertura_broker',
  'comision_sobretasa_broker',
  'comision_renovacion_broker',
  'comision_apertura_master',
  'comision_sobretasa_master',
  'comision_renovacion_master',
  'contacto',
  'email_contacto',
  'telefono_contacto',
  'observaciones'
];

export function downloadFinancierasTemplateClient() {
  const wb = XLSX.utils.book_new();

  const instructionsData = [
    ['INSTRUCCIONES PARA IMPORTACIÓN DE FINANCIERAS Y PRODUCTOS'],
    [''],
    ['ESTRUCTURA: Cada fila representa un PRODUCTO de una financiera para un PERFIL DE CLIENTE específico.'],
    ['Si una financiera tiene el mismo producto para varios perfiles, agregue una fila por perfil.'],
    ['Si una financiera tiene varios productos, agregue una fila por producto.'],
    ['El sistema detecta financieras existentes por nombre y las actualiza automáticamente.'],
    [''],
    ['CAMPOS OBLIGATORIOS (*):'],
    ['- nombre_financiera*: Nombre de la financiera (se usa para buscar si ya existe)'],
    ['- tipo_producto*: Tipo de crédito (ej: Crédito Simple, Crédito PYME, Línea de Crédito, Arrendamiento)'],
    ['- perfil_cliente*: persona_moral, fisica_empresarial, fisica, o sin_sat'],
    [''],
    ['CAMPOS DEL PRODUCTO:'],
    ['- monto_minimo: Financiamiento mínimo en pesos (solo número, ej: 200000)'],
    ['- monto_maximo: Financiamiento máximo en pesos (solo número, ej: 5000000)'],
    ['- plazo_meses: Plazo en meses (ej: 36 o rango como "12-60")'],
    ['- tasa_interes: Tasa de interés % (ej: 18 o rango como "15-24")'],
    ['- comision_apertura: Comisión por apertura % que cobra la financiera al cliente (ej: 2.5)'],
    ['- destinos_credito: Principales destinos separados por punto y coma (ej: Capital de trabajo; Adquisición de activos)'],
    [''],
    ['REQUISITOS PARA EL MATCHING (alimentan la selección inteligente):'],
    ['- edad_minima: Edad mínima del cliente (años)'],
    ['- edad_maxima: Edad máxima del cliente (años)'],
    ['- antiguedad_meses_min: Antigüedad mínima del negocio/empleo (meses)'],
    ['- ingreso_mensual_min: Ingreso mensual mínimo requerido (pesos)'],
    ['- ingreso_anual_min: Ingreso anual mínimo (Persona Moral / PFAE)'],
    ['- ventas_terminal_min: Facturación mensual mínima con terminal bancaria/TPV (pesos)'],
    ['- buro_accionista_min: Score mínimo buró accionista principal (puntos)'],
    ['- buro_empresa_min: Score mínimo buró empresa (puntos)'],
    ['- buro_persona_fisica_min: Score mínimo buró persona física (puntos)'],
    ['- permite_atrasos_buro: si / no (si tolera atrasos o cuentas activas en buró)'],
    ['- tolerancia_atrasos_max: Monto máximo tolerado en atrasos (pesos)'],
    ['- tipo_garantia: Tipos de garantía aceptados (ej: hipotecaria, prendaria, líquida, sin garantía)'],
    ['- requiere_aval: si / no (si exige aval u obligado solidario)'],
    ['- requiere_sat_ciec: si / no (si exige conexión / contraseña CIEC SAT)'],
    ['- requiere_estados_financieros: si / no (si exige estados financieros)'],
    ['- opinion_cumplimiento: solo-positiva o positiva-negativa'],
    ['- participacion_ventas_gob_max: Máx. participación ventas gobierno (ej: menor-20, menor-40, menor-50, menor-60)'],
    ['- requiere_creditos_vigentes: si / no (si exige tener créditos bancarios vigentes)'],
    [''],
    ['INFORMACIÓN OPERATIVA:'],
    ['- giros_prohibidos: Giros no aceptados, separados por punto y coma'],
    ['- presencia: Estados/regiones con presencia (ej: Nacional o CDMX; Jalisco; Nuevo León)'],
    ['- tiempo_respuesta: Tiempo estimado de respuesta (ej: 24-48 horas)'],
    [''],
    ['COMISIONES SUPER ADMIN / PLATAFORMA / MASTER / BROKER (%):'],
    ['- comision_apertura_superadmin: % de comisión de apertura para Super Admin / Plataforma Crédito Negocios'],
    ['- comision_sobretasa_superadmin: % de sobretasa para Super Admin / Plataforma'],
    ['- comision_renovacion_superadmin: % de renovación para Super Admin / Plataforma'],
    ['- comision_apertura_broker: % de comisión de apertura para el bróker originador'],
    ['- comision_sobretasa_broker: % de sobretasa para el bróker originador'],
    ['- comision_renovacion_broker: % de renovación para el bróker originador'],
    ['- comision_apertura_master: % de comisión de apertura para el Master Bróker'],
    ['- comision_sobretasa_master: % de sobretasa para el Master Bróker'],
    ['- comision_renovacion_master: % de renovación para el Master Bróker'],
    [''],
    ['CONTACTO:'],
    ['- contacto: Nombre del contacto principal'],
    ['- email_contacto: Correo electrónico'],
    ['- telefono_contacto: Teléfono'],
    ['- observaciones: Notas adicionales']
  ];

  const instructionsWs = XLSX.utils.aoa_to_sheet(instructionsData);
  instructionsWs['!cols'] = [{ wch: 120 }];
  XLSX.utils.book_append_sheet(wb, instructionsWs, 'Instrucciones');

  const rows = [
    FINANCIERA_HEADERS,
    [
      'Financiera Ejemplo',
      'Crédito Simple',
      'persona_moral',
      200000,
      5000000,
      '12-60',
      '15-24',
      2.5,
      'Capital de trabajo; Adquisición de activos fijos; Remodelación',
      25,
      75,
      24,
      135000,
      1000000,
      50000,
      650,
      620,
      '',
      'no',
      0,
      'hipotecaria; prendaria',
      'si',
      'si',
      'si',
      'solo-positiva',
      'menor-40',
      'si',
      'Casinos; Casas de empeño',
      'Nacional',
      '24-48 horas',
      '4.0',
      '1.5',
      '2.0',
      '2.5',
      '1.0',
      '1.5',
      '1.0',
      '0.5',
      '0.75',
      'Juan Pérez',
      'contacto@financiera.com',
      '5555551234',
      'Ejemplo de registro completo con comisiones y matching rules'
    ],
    [
      'Financiera Ejemplo',
      'Crédito Simple',
      'fisica_empresarial',
      100000,
      3000000,
      '12-48',
      '18-28',
      3.0,
      'Capital de trabajo; Equipamiento',
      21,
      70,
      12,
      80000,
      500000,
      30000,
      630,
      '',
      '',
      'si',
      15000,
      'prendaria; sin garantía',
      'no',
      'si',
      'no',
      'positiva-negativa',
      'menor-20',
      'no',
      'Casinos',
      'Nacional',
      '24-48 horas',
      '3.5',
      '1.2',
      '1.8',
      '2.5',
      '1.0',
      '1.5',
      '1.0',
      '0.5',
      '0.75',
      'Juan Pérez',
      'contacto@financiera.com',
      '5555551234',
      'Misma financiera, perfil PFAE'
    ],
    [
      'Otra Financiera',
      'Crédito PYME',
      'persona_moral',
      500000,
      20000000,
      '12-84',
      '12-18',
      1.5,
      'Capital de trabajo; Expansión; Adquisición de empresas',
      30,
      65,
      36,
      250000,
      2500000,
      100000,
      680,
      650,
      '',
      'no',
      0,
      'hipotecaria',
      'si',
      'si',
      'si',
      'solo-positiva',
      'menor-50',
      'si',
      '',
      'CDMX; Jalisco; Nuevo León',
      '3-5 días',
      '5.0',
      '1.0',
      '2.5',
      '3.0',
      '0.5',
      '2.0',
      '1.5',
      '0.3',
      '1.0',
      'María García',
      'maria@otrafinanciera.com',
      '5555559999',
      'Financiera especializada en PYME grandes'
    ]
  ];

  const ws = XLSX.utils.aoa_to_sheet(rows);
  const colWidths: Record<string, number> = {
    'nombre_financiera': 25,
    'tipo_producto': 20,
    'perfil_cliente': 20,
    'destinos_credito': 40,
    'giros_prohibidos': 30,
    'presencia': 25,
    'observaciones': 35,
    'tipo_garantia': 25,
    'comision_apertura_superadmin': 28,
    'comision_sobretasa_superadmin': 28,
    'comision_renovacion_superadmin': 28,
    'comision_apertura_broker': 24,
    'comision_sobretasa_broker': 24,
    'comision_renovacion_broker': 24,
    'comision_apertura_master': 24,
    'comision_sobretasa_master': 24,
    'comision_renovacion_master': 24,
  };
  ws['!cols'] = FINANCIERA_HEADERS.map(h => ({ wch: colWidths[h] || 18 }));
  XLSX.utils.book_append_sheet(wb, ws, 'Financieras');

  XLSX.writeFile(wb, 'template_financieras_productos.xlsx');
}
